version: '3.8'

services:
    jsmith-syllabuses-server:
      build:
        context: .
        dockerfile: Dockerfile
      image: jsmith-syllabuses-img
      # container_name: jsmith-syllabuses-server
      volumes:
        - .:/usr/src/app
        - /usr/src/app/node_modules
      ports:
        - "8080:8080"
      depends_on:
        - mongo
      env_file: .env
      environment:
        - MONGO_HOSTNAME=$MONGO_HOSTNAME
        - MONGO_PORT=$MONGO_PORT
        - MONGO_DB=$MONGO_DB
    mongo:
      image: mongo
      container_name: jsmith-syllabuses-mongodb
      ports:
        - "27017:27017"
